version: '3.9'

services:
  vidly-frontend:
    build: .
    image: ${DOCKERHUB_USERNAME}/vidly-frontend:${BUILD_NUMBER}
    networks:
      - vidly-app
    environment:
      PORT: 3000
    ports:
      - "4000:3000"
    # depends_on:
    #   - vidly-backend
    init: true

networks:
  vidly-app:
    driver: bridge
